import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'index',
    {
      type: 'category',
      label: '⚛️ React',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: '🌱 Fundamentals',
          items: [
            {type: 'autogenerated', dirName: 'react/01-core-hooks'},
            {type: 'autogenerated', dirName: 'react/02-performance-hooks'},
          ],
        },
        {
          type: 'category',
          label: '✨ React 19 Features',
          items: [
            {type: 'autogenerated', dirName: 'react/03-react19-action-hooks'},
            {type: 'autogenerated', dirName: 'react/09-react-19-2-additions'},
          ],
        },
        {
          type: 'category',
          label: '🔗 State, DOM & Server',
          items: [
            {type: 'autogenerated', dirName: 'react/04-context-and-external-stores'},
            {type: 'autogenerated', dirName: 'react/05-dom-and-refs'},
            {type: 'autogenerated', dirName: 'react/06-server-components-and-actions'},
            {type: 'autogenerated', dirName: 'react/07-react-dom-apis'},
          ],
        },
        {
          type: 'category',
          label: '♿ Accessibility & Debugging',
          items: [
            {type: 'autogenerated', dirName: 'react/08-id-accessibility-debug'},
          ],
        },
        {
          type: 'category',
          label: '🍳 Recipes',
          items: [
            {type: 'autogenerated', dirName: 'react/10-real-world-workflows-and-recipes'},
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '▲ Next.js',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: '🌱 Routing Fundamentals',
          items: [
            {type: 'autogenerated', dirName: 'nextjs/01-routing-fundamentals'},
            {type: 'autogenerated', dirName: 'nextjs/02-advanced-routing-patterns'},
            {type: 'autogenerated', dirName: 'nextjs/11-legacy-pages-router'},
          ],
        },
        {
          type: 'category',
          label: '⚙️ Rendering & Data',
          items: [
            {type: 'autogenerated', dirName: 'nextjs/03-rendering-strategies'},
            {type: 'autogenerated', dirName: 'nextjs/04-data-fetching'},
            {type: 'autogenerated', dirName: 'nextjs/05-server-actions-and-mutations'},
            {type: 'autogenerated', dirName: 'nextjs/06-caching-architecture'},
            {type: 'autogenerated', dirName: 'nextjs/12-rendering-runtimes'},
          ],
        },
        {
          type: 'category',
          label: '🎨 Customization & Config',
          items: [
            {type: 'autogenerated', dirName: 'nextjs/07-metadata-and-seo'},
            {type: 'autogenerated', dirName: 'nextjs/08-middleware'},
            {type: 'autogenerated', dirName: 'nextjs/09-route-handlers'},
            {type: 'autogenerated', dirName: 'nextjs/13-configuration'},
          ],
        },
        {
          type: 'category',
          label: '⚡ Performance & Advanced',
          items: [
            {type: 'autogenerated', dirName: 'nextjs/10-optimization-apis'},
            {type: 'autogenerated', dirName: 'nextjs/15-advanced-patterns'},
          ],
        },
        {
          type: 'category',
          label: '🚀 Deployment & Migration',
          items: [
            {type: 'autogenerated', dirName: 'nextjs/14-deployment-and-build'},
            {type: 'autogenerated', dirName: 'nextjs/16-migration-recipes'},
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '⚡ JavaScript',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: '🌱 Core Language Fundamentals',
          items: [
            {type: 'autogenerated', dirName: 'javascript/01-core-language-fundamentals'},
            {type: 'autogenerated', dirName: 'javascript/02-execution-context-and-scope'},
            {type: 'autogenerated', dirName: 'javascript/03-the-this-keyword'},
            {type: 'autogenerated', dirName: 'javascript/04-functions-in-depth'},
          ],
        },
        {
          type: 'category',
          label: '🧩 OOP & Data Structures',
          items: [
            {type: 'autogenerated', dirName: 'javascript/05-prototypes-and-oop'},
            {type: 'autogenerated', dirName: 'javascript/12-collections-and-data-structures'},
          ],
        },
        {
          type: 'category',
          label: '⏱️ Async & Concurrency',
          items: [
            {type: 'autogenerated', dirName: 'javascript/06-asynchronous-javascript'},
            {type: 'autogenerated', dirName: 'javascript/07-event-loop-deep-dive'},
            {type: 'autogenerated', dirName: 'javascript/08-iterables-and-generators'},
          ],
        },
        {
          type: 'category',
          label: '✨ Modern JS & Modules',
          items: [
            {type: 'autogenerated', dirName: 'javascript/10-modules'},
            {type: 'autogenerated', dirName: 'javascript/11-modern-es-features'},
            {type: 'autogenerated', dirName: 'javascript/15-advanced-meta-programming'},
          ],
        },
        {
          type: 'category',
          label: '🌐 Browser & Runtime',
          items: [
            {type: 'autogenerated', dirName: 'javascript/09-memory-management'},
            {type: 'autogenerated', dirName: 'javascript/13-browser-apis-and-dom'},
            {type: 'autogenerated', dirName: 'javascript/14-error-handling'},
          ],
        },
        {
          type: 'category',
          label: '🍳 Recipes',
          items: [
            {type: 'autogenerated', dirName: 'javascript/17-real-world-workflows-and-recipes'},
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '🔷 TypeScript',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: '🌱 Core Type System',
          items: [
            {type: 'autogenerated', dirName: 'typescript/01-core-type-system'},
            {type: 'autogenerated', dirName: 'typescript/02-structural-typing'},
            {type: 'autogenerated', dirName: 'typescript/03-interfaces-and-type-aliases'},
          ],
        },
        {
          type: 'category',
          label: '🧬 Generics & Functions',
          items: [
            {type: 'autogenerated', dirName: 'typescript/04-functions-and-generics'},
            {type: 'autogenerated', dirName: 'typescript/05-advanced-generics'},
          ],
        },
        {
          type: 'category',
          label: '🛠️ Type Manipulation',
          items: [
            {type: 'autogenerated', dirName: 'typescript/06-utility-types'},
            {type: 'autogenerated', dirName: 'typescript/07-mapped-types'},
            {type: 'autogenerated', dirName: 'typescript/08-template-literal-types'},
            {type: 'autogenerated', dirName: 'typescript/09-type-narrowing-and-guards'},
          ],
        },
        {
          type: 'category',
          label: '🧩 OOP & Modules',
          items: [
            {type: 'autogenerated', dirName: 'typescript/10-classes-and-oop'},
            {type: 'autogenerated', dirName: 'typescript/11-enums-and-const-assertions'},
            {type: 'autogenerated', dirName: 'typescript/12-modules-and-declarations'},
          ],
        },
        {
          type: 'category',
          label: '🎨 Configuration & Integration',
          items: [
            {type: 'autogenerated', dirName: 'typescript/13-configuration'},
            {type: 'autogenerated', dirName: 'typescript/14-react-typescript-integration'},
          ],
        },
        {
          type: 'category',
          label: '🚀 Advanced Patterns & Migration',
          items: [
            {type: 'autogenerated', dirName: 'typescript/15-advanced-patterns'},
            {type: 'autogenerated', dirName: 'typescript/16-migration-recipes'},
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '🎨 CSS',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: '🌱 Fundamentals',
          items: [
            {type: 'autogenerated', dirName: 'css/01-cascade-specificity-and-inheritance'},
            {type: 'autogenerated', dirName: 'css/02-box-model-and-sizing'},
            {type: 'autogenerated', dirName: 'css/03-visual-formatting-and-display'},
            {type: 'autogenerated', dirName: 'css/09-selectors-and-pseudo-patterns'},
          ],
        },
        {
          type: 'category',
          label: '📐 Layout Systems',
          items: [
            {type: 'autogenerated', dirName: 'css/04-flexbox-deep-dive'},
            {type: 'autogenerated', dirName: 'css/05-css-grid-deep-dive'},
            {type: 'autogenerated', dirName: 'css/06-positioning-and-stacking'},
            {type: 'autogenerated', dirName: 'css/07-floats-multicolumn-and-legacy'},
            {type: 'autogenerated', dirName: 'css/08-responsive-and-container-queries'},
          ],
        },
        {
          type: 'category',
          label: '🎨 Typography, Color & Theming',
          items: [
            {type: 'autogenerated', dirName: 'css/10-typography-and-text-layout'},
            {type: 'autogenerated', dirName: 'css/11-color-backgrounds-and-borders'},
            {type: 'autogenerated', dirName: 'css/13-custom-properties-functions-and-at-rules'},
          ],
        },
        {
          type: 'category',
          label: '🎬 Motion, Forms & Interaction',
          items: [
            {type: 'autogenerated', dirName: 'css/12-transforms-transitions-and-animations'},
            {type: 'autogenerated', dirName: 'css/15-forms-ui-controls-and-interaction'},
          ],
        },
        {
          type: 'category',
          label: '♿ Accessibility & I18n',
          items: [
            {type: 'autogenerated', dirName: 'css/16-accessibility-i18n-and-print'},
          ],
        },
        {
          type: 'category',
          label: '⚡ Performance & Architecture',
          items: [
            {type: 'autogenerated', dirName: 'css/17-performance-containment-and-rendering'},
            {type: 'autogenerated', dirName: 'css/18-architecture-touchpoints'},
          ],
        },
        {
          type: 'category',
          label: '🍳 Production Patterns & Recipes',
          items: [
            {type: 'autogenerated', dirName: 'css/14-css-tricks-and-production-patterns'},
            {type: 'autogenerated', dirName: 'css/19-real-world-workflows-and-recipes'},
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '🏛️ Frontend Architecture',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: '🌱 Foundations',
          items: [
            {type: 'autogenerated', dirName: 'frontend-architecture/01-project-structure-and-organization'},
            {type: 'autogenerated', dirName: 'frontend-architecture/02-component-architecture'},
            {type: 'autogenerated', dirName: 'frontend-architecture/03-state-management-decision-tree'},
          ],
        },
        {
          type: 'category',
          label: '🔗 Data & Styling Architecture',
          items: [
            {type: 'autogenerated', dirName: 'frontend-architecture/04-data-layer-and-api-architecture'},
            {type: 'autogenerated', dirName: 'frontend-architecture/05-routing-and-navigation-architecture'},
            {type: 'autogenerated', dirName: 'frontend-architecture/06-styling-architecture'},
          ],
        },
        {
          type: 'category',
          label: '📈 Scaling The Org',
          items: [
            {type: 'autogenerated', dirName: 'frontend-architecture/07-monorepo-and-multi-app-strategy'},
            {type: 'autogenerated', dirName: 'frontend-architecture/08-environment-and-configuration-management'},
            {type: 'autogenerated', dirName: 'frontend-architecture/09-authentication-and-authorization-architecture'},
          ],
        },
        {
          type: 'category',
          label: '🛡️ Resilience & Operations',
          items: [
            {type: 'autogenerated', dirName: 'frontend-architecture/10-error-handling-and-resilience'},
            {type: 'autogenerated', dirName: 'frontend-architecture/11-observability-and-monitoring'},
            {type: 'autogenerated', dirName: 'frontend-architecture/12-ci-cd-pipeline-design'},
          ],
        },
        {
          type: 'category',
          label: '⚡ Performance & Team Practices',
          items: [
            {type: 'autogenerated', dirName: 'frontend-architecture/13-testing-strategy'},
            {type: 'autogenerated', dirName: 'frontend-architecture/14-performance-and-scalability-patterns'},
            {type: 'autogenerated', dirName: 'frontend-architecture/15-team-and-collaboration-practices'},
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '🔄 TanStack Query',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: '🌱 Fundamentals',
          items: [
            {type: 'autogenerated', dirName: 'tanstack-query/01-core-concepts'},
            {type: 'autogenerated', dirName: 'tanstack-query/02-usequery-deep-dive'},
            {type: 'autogenerated', dirName: 'tanstack-query/03-query-states'},
          ],
        },
        {
          type: 'category',
          label: '💾 Caching & Invalidation',
          items: [
            {type: 'autogenerated', dirName: 'tanstack-query/04-caching-and-invalidation'},
            {type: 'autogenerated', dirName: 'tanstack-query/06-background-refetching'},
            {type: 'autogenerated', dirName: 'tanstack-query/13-global-configuration'},
          ],
        },
        {
          type: 'category',
          label: '✍️ Mutations & Optimistic Updates',
          items: [
            {type: 'autogenerated', dirName: 'tanstack-query/05-usemutation'},
            {type: 'autogenerated', dirName: 'tanstack-query/14-optimistic-updates-patterns'},
          ],
        },
        {
          type: 'category',
          label: '🔀 Advanced Query Patterns',
          items: [
            {type: 'autogenerated', dirName: 'tanstack-query/07-pagination-and-infinite-queries'},
            {type: 'autogenerated', dirName: 'tanstack-query/08-dependent-and-parallel-queries'},
            {type: 'autogenerated', dirName: 'tanstack-query/09-prefetching-and-ssr'},
            {type: 'autogenerated', dirName: 'tanstack-query/10-suspense-integration'},
            {type: 'autogenerated', dirName: 'tanstack-query/12-query-cancellation'},
          ],
        },
        {
          type: 'category',
          label: '🧪 Testing & Debugging',
          items: [
            {type: 'autogenerated', dirName: 'tanstack-query/11-devtools'},
            {type: 'autogenerated', dirName: 'tanstack-query/15-testing-tanstack-query'},
          ],
        },
        {
          type: 'category',
          label: '🚀 Migration',
          items: [
            {type: 'autogenerated', dirName: 'tanstack-query/16-migration-recipes'},
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '📦 Redux Toolkit',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: '🌱 Fundamentals',
          items: [
            {type: 'autogenerated', dirName: 'redux-toolkit/01-store-setup'},
            {type: 'autogenerated', dirName: 'redux-toolkit/02-slices-and-actions'},
            {type: 'autogenerated', dirName: 'redux-toolkit/08-immutability-and-immer'},
          ],
        },
        {
          type: 'category',
          label: '🌐 Data Fetching',
          items: [
            {type: 'autogenerated', dirName: 'redux-toolkit/03-async-thunks'},
            {type: 'autogenerated', dirName: 'redux-toolkit/04-rtk-query'},
          ],
        },
        {
          type: 'category',
          label: '🔗 Derived State & Middleware',
          items: [
            {type: 'autogenerated', dirName: 'redux-toolkit/05-selectors-and-normalization'},
            {type: 'autogenerated', dirName: 'redux-toolkit/06-middleware'},
          ],
        },
        {
          type: 'category',
          label: '🧩 Integration & Types',
          items: [
            {type: 'autogenerated', dirName: 'redux-toolkit/07-react-redux-integration'},
            {type: 'autogenerated', dirName: 'redux-toolkit/09-typescript-integration'},
          ],
        },
        {
          type: 'category',
          label: '⚡ Performance, Testing & Debugging',
          items: [
            {type: 'autogenerated', dirName: 'redux-toolkit/10-devtools-and-debugging'},
            {type: 'autogenerated', dirName: 'redux-toolkit/11-code-splitting'},
            {type: 'autogenerated', dirName: 'redux-toolkit/12-testing'},
          ],
        },
        {
          type: 'category',
          label: '🚀 Migration',
          items: [
            {type: 'autogenerated', dirName: 'redux-toolkit/13-migration'},
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '🚀 Web Vitals & Performance',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: '🌱 Fundamentals',
          items: [
            {type: 'autogenerated', dirName: 'web-vitals-performance/01-core-web-vitals'},
            {type: 'autogenerated', dirName: 'web-vitals-performance/02-legacy-and-lab-measurement'},
            {type: 'autogenerated', dirName: 'web-vitals-performance/03-real-user-monitoring'},
          ],
        },
        {
          type: 'category',
          label: '⚡ Core Vitals Optimization',
          items: [
            {type: 'autogenerated', dirName: 'web-vitals-performance/04-lcp-optimization'},
            {type: 'autogenerated', dirName: 'web-vitals-performance/05-inp-optimization'},
            {type: 'autogenerated', dirName: 'web-vitals-performance/06-cls-optimization'},
          ],
        },
        {
          type: 'category',
          label: '📦 Loading & Rendering',
          items: [
            {type: 'autogenerated', dirName: 'web-vitals-performance/07-loading-and-rendering-performance'},
            {type: 'autogenerated', dirName: 'web-vitals-performance/08-bundle-and-media-optimization'},
          ],
        },
        {
          type: 'category',
          label: '📊 Production Monitoring',
          items: [
            {type: 'autogenerated', dirName: 'web-vitals-performance/09-caching-and-production-monitoring'},
            {type: 'autogenerated', dirName: 'web-vitals-performance/10-budgets-and-advanced-diagnostics'},
          ],
        },
        {
          type: 'category',
          label: '🍳 Recipes',
          items: [
            {type: 'autogenerated', dirName: 'web-vitals-performance/16-real-world-workflows-and-recipes'},
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '⚡ Vite',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: '🌱 Fundamentals',
          items: [
            {type: 'autogenerated', dirName: 'vite/01-core-architecture'},
            {type: 'autogenerated', dirName: 'vite/02-cli-and-scaffolding'},
            {type: 'autogenerated', dirName: 'vite/03-configuration'},
          ],
        },
        {
          type: 'category',
          label: '🏗️ Dev & Build Pipeline',
          items: [
            {type: 'autogenerated', dirName: 'vite/04-dev-server-mechanics'},
            {type: 'autogenerated', dirName: 'vite/05-build-system-rollup'},
            {type: 'autogenerated', dirName: 'vite/06-asset-handling'},
            {type: 'autogenerated', dirName: 'vite/09-css-handling'},
          ],
        },
        {
          type: 'category',
          label: '🎨 Customization & Environments',
          items: [
            {type: 'autogenerated', dirName: 'vite/07-env-variables-and-modes'},
            {type: 'autogenerated', dirName: 'vite/08-plugin-system'},
            {type: 'autogenerated', dirName: 'vite/12-path-resolution-and-aliases'},
          ],
        },
        {
          type: 'category',
          label: '🌐 Advanced Runtime',
          items: [
            {type: 'autogenerated', dirName: 'vite/10-ssr-support'},
            {type: 'autogenerated', dirName: 'vite/13-worker-and-wasm-support'},
          ],
        },
        {
          type: 'category',
          label: '⚡ Performance & Testing',
          items: [
            {type: 'autogenerated', dirName: 'vite/11-optimization-and-performance'},
            {type: 'autogenerated', dirName: 'vite/14-testing-integration'},
          ],
        },
        {
          type: 'category',
          label: '🚀 Deployment & Migration',
          items: [
            {type: 'autogenerated', dirName: 'vite/15-deployment-considerations'},
            {type: 'autogenerated', dirName: 'vite/16-migration-recipes'},
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '⚙️ Webpack',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: '🌱 Fundamentals',
          items: [
            {type: 'autogenerated', dirName: 'webpack/01-core-concepts'},
            {type: 'autogenerated', dirName: 'webpack/02-configuration'},
            {type: 'autogenerated', dirName: 'webpack/03-module-resolution'},
          ],
        },
        {
          type: 'category',
          label: '📦 Loaders & Assets',
          items: [
            {type: 'autogenerated', dirName: 'webpack/04-loaders'},
            {type: 'autogenerated', dirName: 'webpack/05-asset-modules'},
          ],
        },
        {
          type: 'category',
          label: '🧩 Plugins & Code Splitting',
          items: [
            {type: 'autogenerated', dirName: 'webpack/06-plugins'},
            {type: 'autogenerated', dirName: 'webpack/07-code-splitting'},
            {type: 'autogenerated', dirName: 'webpack/11-module-federation'},
          ],
        },
        {
          type: 'category',
          label: '⚡ Optimization & Performance',
          items: [
            {type: 'autogenerated', dirName: 'webpack/08-optimization'},
            {type: 'autogenerated', dirName: 'webpack/10-caching-strategies'},
            {type: 'autogenerated', dirName: 'webpack/14-performance-analysis'},
          ],
        },
        {
          type: 'category',
          label: '🛠️ Dev Experience & Debugging',
          items: [
            {type: 'autogenerated', dirName: 'webpack/09-dev-server-and-hmr'},
            {type: 'autogenerated', dirName: 'webpack/12-source-maps'},
          ],
        },
        {
          type: 'category',
          label: '🏗️ Advanced Configuration',
          items: [
            {type: 'autogenerated', dirName: 'webpack/13-multi-config-and-environment'},
            {type: 'autogenerated', dirName: 'webpack/15-advanced-custom-tooling'},
          ],
        },
        {
          type: 'category',
          label: '🍳 Recipes',
          items: [
            {type: 'autogenerated', dirName: 'webpack/16-real-world-workflows-and-recipes'},
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '🎞️ Framer Motion',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: '🌱 Fundamentals',
          items: [
            {type: 'autogenerated', dirName: 'framer-motion/01-core-concepts'},
            {type: 'autogenerated', dirName: 'framer-motion/02-basic-animation-props'},
            {type: 'autogenerated', dirName: 'framer-motion/03-transition-types'},
          ],
        },
        {
          type: 'category',
          label: '🎬 Declarative Animation',
          items: [
            {type: 'autogenerated', dirName: 'framer-motion/04-variants'},
            {type: 'autogenerated', dirName: 'framer-motion/05-gestures'},
            {type: 'autogenerated', dirName: 'framer-motion/06-animatepresence'},
            {type: 'autogenerated', dirName: 'framer-motion/07-layout-animations'},
          ],
        },
        {
          type: 'category',
          label: '🧬 Advanced Motion Techniques',
          items: [
            {type: 'autogenerated', dirName: 'framer-motion/08-scroll-linked-animations'},
            {type: 'autogenerated', dirName: 'framer-motion/09-motion-values'},
            {type: 'autogenerated', dirName: 'framer-motion/10-animation-controls'},
            {type: 'autogenerated', dirName: 'framer-motion/11-keyframes'},
            {type: 'autogenerated', dirName: 'framer-motion/12-svg-animations'},
            {type: 'autogenerated', dirName: 'framer-motion/13-orchestration-and-staggering'},
          ],
        },
        {
          type: 'category',
          label: '⚡ Performance & Advanced Patterns',
          items: [
            {type: 'autogenerated', dirName: 'framer-motion/14-performance-considerations'},
            {type: 'autogenerated', dirName: 'framer-motion/15-advanced-patterns'},
          ],
        },
        {
          type: 'category',
          label: '🍳 Recipes',
          items: [
            {type: 'autogenerated', dirName: 'framer-motion/16-real-world-workflows-and-recipes'},
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '📖 Storybook',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: '🌱 Fundamentals',
          items: [
            {type: 'autogenerated', dirName: 'storybook/01-core-concepts'},
            {type: 'autogenerated', dirName: 'storybook/02-story-anatomy'},
            {type: 'autogenerated', dirName: 'storybook/04-controls-and-args'},
          ],
        },
        {
          type: 'category',
          label: '🧩 Ecosystem & Composition',
          items: [
            {type: 'autogenerated', dirName: 'storybook/03-addons-ecosystem'},
            {type: 'autogenerated', dirName: 'storybook/09-decorators'},
            {type: 'autogenerated', dirName: 'storybook/10-composition-and-design-systems'},
            {type: 'autogenerated', dirName: 'storybook/12-multi-framework-support'},
          ],
        },
        {
          type: 'category',
          label: '🎨 Customization & Theming',
          items: [
            {type: 'autogenerated', dirName: 'storybook/17-theming-colors-and-fonts'},
          ],
        },
        {
          type: 'category',
          label: '🧪 Testing',
          items: [
            {type: 'autogenerated', dirName: 'storybook/05-interaction-testing'},
            {type: 'autogenerated', dirName: 'storybook/06-visual-testing'},
            {type: 'autogenerated', dirName: 'storybook/07-accessibility-testing'},
            {type: 'autogenerated', dirName: 'storybook/11-testing-integration'},
          ],
        },
        {
          type: 'category',
          label: '📝 Documentation & Config',
          items: [
            {type: 'autogenerated', dirName: 'storybook/08-documentation'},
            {type: 'autogenerated', dirName: 'storybook/13-build-and-configuration'},
          ],
        },
        {
          type: 'category',
          label: '🚀 Deployment',
          items: [
            {type: 'autogenerated', dirName: 'storybook/14-publishing-and-deployment'},
          ],
        },
        {
          type: 'category',
          label: '🍳 Advanced & Recipes',
          items: [
            {type: 'autogenerated', dirName: 'storybook/15-advanced-patterns'},
            {type: 'autogenerated', dirName: 'storybook/16-real-world-workflows-and-recipes'},
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '🧪 Jest & RTL',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: '🌱 Jest Fundamentals',
          items: [
            {type: 'autogenerated', dirName: 'jest-rtl/01-jest-core-concepts'},
            {type: 'autogenerated', dirName: 'jest-rtl/02-assertions-and-matchers'},
            {type: 'autogenerated', dirName: 'jest-rtl/03-mocking'},
          ],
        },
        {
          type: 'category',
          label: '⏱️ Async & Snapshot Testing',
          items: [
            {type: 'autogenerated', dirName: 'jest-rtl/04-async-testing'},
            {type: 'autogenerated', dirName: 'jest-rtl/05-snapshot-testing'},
            {type: 'autogenerated', dirName: 'jest-rtl/06-coverage-and-configuration'},
          ],
        },
        {
          type: 'category',
          label: '🌱 RTL Fundamentals',
          items: [
            {type: 'autogenerated', dirName: 'jest-rtl/07-rtl-core-philosophy'},
            {type: 'autogenerated', dirName: 'jest-rtl/08-rtl-queries'},
            {type: 'autogenerated', dirName: 'jest-rtl/09-user-interaction'},
          ],
        },
        {
          type: 'category',
          label: '🛠️ Advanced Testing Patterns',
          items: [
            {type: 'autogenerated', dirName: 'jest-rtl/10-async-utilities'},
            {type: 'autogenerated', dirName: 'jest-rtl/11-custom-render'},
            {type: 'autogenerated', dirName: 'jest-rtl/12-mocking-network-requests'},
            {type: 'autogenerated', dirName: 'jest-rtl/13-testing-hooks'},
          ],
        },
        {
          type: 'category',
          label: '♿ Accessibility & Debugging',
          items: [
            {type: 'autogenerated', dirName: 'jest-rtl/14-accessibility-testing'},
            {type: 'autogenerated', dirName: 'jest-rtl/15-debugging-tests'},
          ],
        },
        {
          type: 'category',
          label: '🍳 Recipes',
          items: [
            {type: 'autogenerated', dirName: 'jest-rtl/16-real-world-workflows-and-recipes'},
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '🎭 Playwright',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: '🌱 Fundamentals',
          items: [
            {type: 'autogenerated', dirName: 'playwright/01-core-architecture'},
            {type: 'autogenerated', dirName: 'playwright/02-test-runner'},
            {type: 'autogenerated', dirName: 'playwright/03-locators'},
          ],
        },
        {
          type: 'category',
          label: '🖱️ Interactions & Assertions',
          items: [
            {type: 'autogenerated', dirName: 'playwright/04-actions-and-interactions'},
            {type: 'autogenerated', dirName: 'playwright/05-auto-waiting-and-assertions'},
            {type: 'autogenerated', dirName: 'playwright/06-navigation-and-network'},
          ],
        },
        {
          type: 'category',
          label: '🔐 Test Setup & Isolation',
          items: [
            {type: 'autogenerated', dirName: 'playwright/07-authentication-and-state'},
            {type: 'autogenerated', dirName: 'playwright/08-fixtures-and-test-isolation'},
          ],
        },
        {
          type: 'category',
          label: '📸 Visual, Component & API Testing',
          items: [
            {type: 'autogenerated', dirName: 'playwright/09-visual-and-screenshot-testing'},
            {type: 'autogenerated', dirName: 'playwright/12-component-testing'},
            {type: 'autogenerated', dirName: 'playwright/13-api-testing'},
          ],
        },
        {
          type: 'category',
          label: '🛠️ Debugging & Scaling',
          items: [
            {type: 'autogenerated', dirName: 'playwright/10-debugging-tools'},
            {type: 'autogenerated', dirName: 'playwright/11-parallelism-and-sharding'},
          ],
        },
        {
          type: 'category',
          label: '🚀 CI & Advanced',
          items: [
            {type: 'autogenerated', dirName: 'playwright/14-ci-integration'},
            {type: 'autogenerated', dirName: 'playwright/15-advanced-patterns'},
          ],
        },
        {
          type: 'category',
          label: '🍳 Recipes',
          items: [
            {type: 'autogenerated', dirName: 'playwright/16-real-world-workflows-and-recipes'},
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '🔧 Git',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: '🌱 Fundamentals',
          items: [
            {type: 'autogenerated', dirName: 'git/01-core-architecture'},
            {type: 'autogenerated', dirName: 'git/02-plumbing-vs-porcelain'},
          ],
        },
        {
          type: 'category',
          label: '🌿 Branching & History',
          items: [
            {type: 'autogenerated', dirName: 'git/03-branching-merging-rebase'},
            {type: 'autogenerated', dirName: 'git/04-history-rewriting-forensics'},
          ],
        },
        {
          type: 'category',
          label: '🏢 Team & Scale Workflows',
          items: [
            {type: 'autogenerated', dirName: 'git/05-enterprise-workflows-monorepos'},
            {type: 'autogenerated', dirName: 'git/06-remotes-and-maintenance'},
          ],
        },
        {
          type: 'category',
          label: '🍳 Recipes',
          items: [
            {type: 'autogenerated', dirName: 'git/07-real-world-workflows-and-recipes'},
          ],
        },
      ],
    },
  ],
};

export default sidebars;
